name: Docker Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: SSH to EC2 and build docker image
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /srv/flipmap-backend
            git pull origin main
            docker build -t flipmap-backend .
            docker run --env-file /srv/flipmap-backend/.env -d flipmap-api
